### ISSUE TITLE
What if mFaces is null ? 

### ISSUE THREAD

**Issue by vinaykumar2197** [murali129/Eye-blink-detector#1]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object reference
       at in.vinay.EyeBlinkDetection.FaceOverlayView.isEyeBlinked(SourceFile:134)
       at in.vinay.EyeBlinkDetection.FaceOverlayView.setBitmap(SourceFile:78)
       at in.vinay.EyeBlinkDetection.CameraActivity.setBitMapImage(SourceFile:358)
       at in.vinay.EyeBlinkDetection.FaceScanner.onPreviewFrame(SourceFile:357)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1572)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6671)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by vinaykumar2197** [comment]
Would this code be okay ? 

>  if(mFaces!=null) {
>             if (mFaces.size() == 0)
>                 return false;
> 
>             Face face = mFaces.valueAt(0);
>             float currentLeftEyeOpenProbability = face.getIsLeftEyeOpenProbability();
>             float currentRightEyeOpenProbability = face.getIsRightEyeOpenProbability();
>             if (currentLeftEyeOpenProbability == -1.0 || currentRightEyeOpenProbability == -1.0) {
>                 return false;
>             }
> 
>             if (leftEyeOpenProbability > 0.9 || rightEyeOpenProbability > 0.9) {
>                 boolean blinked = false;
>                 if (currentLeftEyeOpenProbability < 0.6 || rightEyeOpenProbability < 0.6) {
>                     blinked = true;
>                 }
>                 leftEyeOpenProbability = currentLeftEyeOpenProbability;
>                 rightEyeOpenProbability = currentRightEyeOpenProbability;
>                 return blinked;
>             } else {
>                 leftEyeOpenProbability = currentLeftEyeOpenProbability;
>                 rightEyeOpenProbability = currentRightEyeOpenProbability;
>                 return false;
>             }
>         }
>         else{
>             return false;
>         }
